services:
  mongodb:
    image: mongo:6.0.27-jammy
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      # غيرنا السطر ده عشان نستخدم الـ Volume اللي عرفناه تحت
      - mongodb_data:/data/db

    networks: 
      - backend

    restart: always

networks:
  backend: 

# ضيفنا الجزء ده عشان نعرف الـ Volume المستقل
volumes:
  mongodb_data: